### ISSUE TITLE
Test other correlation methods

### ISSUE THREAD

**Issue by jrsmith02** [ligovirgo/gwdetchar#14]
Since we might not want to test only for purely linear correlation, we might consider using other correlation statics such as: http://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.spearmanr.html
To be scoped out by Josh and Michelle in summer 2016 (not to be read sarcastically in the future if the date is much beyond summer 2016 and we haven't done it).

**Comment by jrsmith02** [comment]
There are other correlation methods to test, specifically ones that help us identify correlations between channels with a squared relationship, or some phase lag. But the above one example was implemented in [22](https://github.com/ligovirgo/gwdetchar/pull/22).

**Comment by duncanmmacleod** [comment]
@jrsmith02, given that #22 was merged, can this issue be closed?

**Comment by jrsmith02** [comment]
Yes, we can close this, though I think we should continue to look at other correlation methods such as copula https://en.wikipedia.org/wiki/Copula_%28probability_theory%29. But that requires more research.
