### ISSUE TITLE
in gwdetchar-slow-correlation dips in range mess up scaling

### ISSUE THREAD

**Issue by jrsmith02** [ligovirgo/gwdetchar#21]
There is code in gwdetchar-slow-correlation to scale the channels to roughly the same size. But big dips in range can mess up the scaling. For example: https://ldas-jobs.ligo-la.caltech.edu/~jrsmith/detchar/O1/slow-correlation/L1-slow-correlation-1133901917-20700/L1-DMT_SNSH_EFFECTIVE_RANGE_MPC.mean_COMPARISON-1133901917-20700.png

The current code does something like: 
```
# create scaled versions of data to compare to each other
print("-- Creating scaled data")
rangescaled = rangets.detrend()
rangemax = rangescaled.value.max()
darmscaled = darmblrms.detrend()
darmscaled *= (-rangemax / darmscaled.value.max())
```

It would probably be better to do something like, 1. Detrend, 2. calculate the RMS for both channels, 3. scale the channels such that they have the same displayed RMS. I.e. I think we should replace max() above with rms(). The code above is for range and DARM BLRMS, but it should also be done for the auxiliary channel that is being plotted.

**Comment by duncanmmacleod** [comment]
@katerinaleman, can you confirm that PR #24 fixed this issue? If so, please close this ticket.

**Comment by katerinaleman** [comment]
@duncanmmacleod : PR #24 is a significant improvement in the method of scaling data  when in the presence of outliers for the slow-correlation code; however, there is still an interest to search for methods of scaling data that will work even better when the outliers are extremely large. The ticket can be closed for now.
