### ISSUE TITLE
Need to integrate DAC MCT finder into gwdetchar

### ISSUE THREAD

**Issue by duncanmmacleod** [ligovirgo/gwdetchar#26]
@tjmassin has written a nice small package to find so-called Major-Carry Transitions (MCTs) [[0]](https://github.com/tjmassin/DAC-glitch-mon/tree/master/condor), we should integrate this into GWDetChar to enable cross-pollenation with other tools.

**Comment by tjmassin** [comment]
Submitted PR. Style and structure is set up to be consistent the gwdetchar-overflows executable.

https://github.com/ligovirgo/gwdetchar/pull/27
