### ISSUE TITLE
gwdetchar-slow-correlation should remove outliers in the range and BLRMs

### ISSUE THREAD

**Issue by jrsmith02** [ligovirgo/gwdetchar#45]
Currently the ~80Mpc range often contains 1-3 spikes that reach down to nearly zero range due to ETM saturations in a given 24 hour period. This stretches the y-axis scaling and makes it hard to see whether things are really correlated. I think we should remove outlying points and replace them by the mean of neighboring points or something. Stackoverflow suggests: 
`def reject_outliers(data, m=2):
    return data[abs(data - np.mean(data)) < m * np.std(data)]`
That will just remove the points but we want to keep a point there just replace it by the mean of the nearest two points (I'd say point before and after but that would have rare edge effects). @duncanmmacleod do you have any implementation suggestions?

**Comment by jrsmith02** [comment]
An example page where a large spike in BLRMS messes things up is: https://ldas-jobs.ligo-wa.caltech.edu/~jrsmith/detchar/O2/slow-correlations/JeffK-seismic-range-test2/

**Comment by tjma12** [comment]
I mocked up an outlier removal function, I'm going to drop it into my gwdetchar installation and test it. Dotted lines in this example are the mean, and +/- 2 sigma lines.
https://ldas-jobs.ligo.caltech.edu/~thomas.massinger/detchar/smooth_range/RMS.png

**Comment by duncanmmacleod** [comment]
@tjma12, did #47 fix this issue?

**Comment by tjma12** [comment]
Yes, this is fixed by #47
